# Generated by Django 2.2.2 on 2019-07-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('Image', models.FileField(null=True, upload_to='albums/%Y-%m-%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.Artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(null=True, upload_to='albums/%Y-%m-%d/'),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.Album'),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.Image'),
        ),
    ]
